acquire-toolchest-dirs will now attempt to make an educated guess about       the toolchest's location if it is not in $PATH

diff --git a/bin/acquire-toolchest-dirs b/bin/acquire-toolchest-dirs
--- a/bin/acquire-toolchest-dirs
+++ b/bin/acquire-toolchest-dirs
@@ -72,13 +72,24 @@
 #  
 ########10########20########30########40########50########60########70########80
 
+TOOLCHEST_CMD="toolchest"
 command -v toolchest > /dev/null
 if [ $? -ne 0 ] ; then
-  echo "ERROR ATD57: no toolchest binary in PATH"
-  exit 1
+  if [ -e ./toolchest ] ; then
+    TOOLCHEST_CMD="./toolchest"
+  else if [ -e ../toolchest ] ; then 
+    TOOLCHEST_CMD="../toolchest"
+  else if [ -e ./bin/toolchest ] ; then
+    TOOLCHEST_CMD="./bin/toolchest" ;
+  else if [ -e ../bin/toolchest ] ; then
+    TOOLCHEST_CMD="../bin/toolchest" ;
+  else
+    echo "ERROR ATD87: failed to locate toolchest binary"
+    exit 1
+  fi
 fi
 
-DIR=`toolchest dir`
+DIR=`$TOOLCHEST_CMD dir`
 LOCAL="$DIR/local"
 BIN="$DIR/bin"
 LIB="$DIR/lib"
