documented toolchest install dir acquisition

diff --git a/bin/acquire-toolchest-dirs b/bin/acquire-toolchest-dirs
--- a/bin/acquire-toolchest-dirs
+++ b/bin/acquire-toolchest-dirs
@@ -52,7 +52,13 @@
 #  
 ########10########20########30########40########50########60########70########80
 
-DIR=$(realpath `echo $0 | sed 's/toolchest$//g'`/../..)
+command -v toolchest > /dev/null
+if [ $? -ne 0 ] ; then
+  echo "ERROR ATD57: no toolchest binary in PATH"
+  exit 1
+fi
+
+DIR=`toolchest dir`
 LOCAL="$DIR/local"
 BIN="$DIR/bin"
 LIB="$DIR/lib"
