fixed a bug in detecting NET_CDANIELS_TOOLCHEST_DIR on FreeBSD 11

diff --git a/bin/toolchest b/bin/toolchest
--- a/bin/toolchest
+++ b/bin/toolchest
@@ -163,11 +163,17 @@
 
 SYSTEM_INSTALL_DIR="/opt/net.cdaniels.toolchest"
 LOCAL_INSTALL_DIR="$HOME/.net.cdaniels.toolchest"
-TOOLCHEST_VERSION="0.0.1-ALPHA"
+TOOLCHEST_VERSION="0.0.2-ALPHA"
 
 command -v realpath > /dev/null
 if [ $? -ne 0 ] ; then
   echo "ERROR T170: command \"realpath\" is not available"
+  exit 1
+fi
+
+command -v sed > /dev/null
+if [ $? -ne 0 ] ; then
+  echo "ERROR T176: command \"sed\" is not available"
   exit 1
 fi
 
@@ -176,7 +182,11 @@ fi
 if (: "${NET_CDANIELS_TOOLCHEST_DIR?}") 2>/dev/null; then
   printf ""  # do nothing
 else
-  NET_CDANIELS_TOOLCHEST_DIR=$(realpath $0/../..)
+  # this used to be $0/../.. however this breaks on BSD sh, and possible other
+  # shells. The sed command matches "toolchest", followed by a line ending,
+  # and replaces it with nothing. Although this is uglier, it will work on
+  # more systems.
+  NET_CDANIELS_TOOLCHEST_DIR=$(realpath `echo $0 | sed 's/toolchest$//g'`/..)
 fi
 
 if [ "$NET_CDANIELS_TOOLCHEST_DIR" != "$SYSTEM_INSTALL_DIR" ] ; then
