add support for dependancy checking perl modules, and implement audioutil-extract-playlist script

diff --git a/bin/toolchest b/bin/toolchest
--- a/bin/toolchest
+++ b/bin/toolchest
@@ -189,15 +189,21 @@
 #                     match `uname` on the current system, the installer will
 #                     fail.
 #
-#    remote . . . . . a list of remote files which need to be downloaded for the
-#                     package to install. Each line contains the output file name
-#                     and the URL of the file, separated by a single space.
-#                     Either CuRL or Wget will be used to download the file,
-#                     depending on which is available. The output file will be
-#                     placed in a folder named "remote" under the package
-#                     directory. Failure to download the dependancy will NOT
-#                     cause toolchest to abort the installation - you need
-#                     to check for the presencce of your dependancies.
+#    remote . . . . . a list of remote files which need to be downloaded for
+#                     the package to install. Each line contains the output
+#                     file name and the URL of the file, separated by a single
+#                     space. Either CuRL or Wget will be used to download the
+#                     file, depending on which is available. The output file
+#                     will be placed in a folder named "remote" under the
+#                     package directory. Failure to download the dependancy
+#                     will NOT cause toolchest to abort the installation - you
+#                     need to check for the presencce of your dependancies.
+#                     
+#    perl . . . . . . a list of perl modules which need to be installed for the
+#                     package to work. If any are not currently installed, the 
+#                     package installer fails. The toolchest will not attempt 
+#                     to install the module, as on many systems doing so
+#                     requires root access. 
 #
 #    Note that both of these files need to end in a blank line to be parsed
 #    correctly.
@@ -748,75 +754,92 @@ case "$DIRECTIVE" in
         # handle dependancy checking
         if [ -e "$PKG_DIR/dep" ] ; then
 
-          if [ -f "$PKG_DIR/dep/system" ] ; then
-            # validate system dependencies
-            while read -r line ; do
-              printf "INFO: verifying $line is present... "
-              command -v $line > /dev/null
-              if [ $? -ne 0 ] ; then
-                echo "FAIL"
-                echo "ERROR T699: dependancy $line is not present on the system"
-                exit 1
-              fi
-              echo "OK"
-            done < "$PKG_DIR/dep/system"
-          fi  # if [ -f "$PKG_DIR/dep/system" ] ; then
-
-          if [ -f "$PKG_DIR/dep/toolchest" ] ; then
-            # attempt to install toolchest dependencies
-            while read -r line ; do
-              printf "INFO: verifying package $line is installed... "
-              toolchest package list-installed | grep $line > /dev/null
-              # grep will return nonzero if the string is not found
-              if [ $? -eq 0 ] ; then
-                # package is already marked installed
-                echo "OK"
-              else
-                # package not installed, try installing it
-                echo "NOT PRESENT"
-                echo "INFO: will attempt to install package $line"
-                # perform the install
-                toolchest package install $line
+            # system dependencies 
+            if [ -f "$PKG_DIR/dep/system" ] ; then
+              # validate system dependencies
+              while read -r line ; do
+                printf "INFO: verifying $line is present... "
+                command -v $line > /dev/null
                 if [ $? -ne 0 ] ; then
-                  echo "ERROR T717: failed to install dependency $line"
+                  echo "FAIL"
+                  echo "ERROR T699: dependancy $line is not present on the system"
                   exit 1
                 fi
-              fi
-            done < "$PKG_DIR/dep/toolchest"
-          fi  # if [ -f "$PKG_DIR/dep/toolchest" ] ; then
-
-          # handle OS validation
-          if [ -f "$PKG_DIR/dep/uname" ] ; then
-            printf "INFO: validating OS requirements... "
-            grep `uname` < "$PKG_DIR/dep/uname" > /dev/null
-            if [ $? -eq 0 ] ; then
-              echo "OK"
-            else
-              echo "ERROR: OS `uname` is not supported by this package!"
-              exit 1
-            fi
-          fi  # if [ -f "$PKG_DIR/dep/uname" ] ; then
-
-          # attempt to download any artifacts required
-          if [ -f "$PKG_DIR/dep/remote" ] ; then
-            mkdir "$PKG_DIR/remote"
-            DOWNLOAD_CMD="$NET_CDANIELS_TOOLCHEST_DIR/bin/download"
-            if [ ! -f "$DOWNLOAD_CMD" ] ; then
-              echo "ERROR T789: unable to locate download command"
-            else
+                echo "OK"
+              done < "$PKG_DIR/dep/system"
+            fi  # if [ -f "$PKG_DIR/dep/system" ] ; then
+  
+            # toolchest package dependencies 
+            if [ -f "$PKG_DIR/dep/toolchest" ] ; then
+              # attempt to install toolchest dependencies
               while read -r line ; do
-                ARTIFACT_NAME=`echo $line | cut -d\  -f 1`
-                ARTIFACT_URL=`echo $line | cut -d\  -f 2`
-                echo "INFO: preparing to download dependancy: $ARTIFACT_NAME"
-                "$DOWNLOAD_CMD" "$ARTIFACT_URL" "$PKG_DIR/remote/$ARTIFACT_NAME"
+                printf "INFO: verifying package $line is installed... "
+                toolchest package list-installed | grep $line > /dev/null
+                # grep will return nonzero if the string is not found
                 if [ $? -eq 0 ] ; then
-                  echo "INFO: successfully downloaded dependancy $ARTIFACT_NAME."
+                  # package is already marked installed
+                  echo "OK"
                 else
-                  echo "ERROR: FAILED to download dependancy $ARTIFACT_NAME"
+                  # package not installed, try installing it
+                  echo "NOT PRESENT"
+                  echo "INFO: will attempt to install package $line"
+                  # perform the install
+                  toolchest package install $line
+                  if [ $? -ne 0 ] ; then
+                    echo "ERROR T717: failed to install dependency $line"
+                    exit 1
+                  fi
                 fi
-              done < "$PKG_DIR/dep/remote"
-            fi  # if [ ! -f "$DOWNLOAD_CMD" ] ; then
-          fi  # if [ -f "$PKG_DIR/dep/remote" ] ; then
+              done < "$PKG_DIR/dep/toolchest"
+            fi  # if [ -f "$PKG_DIR/dep/toolchest" ] ; then
+  
+            # handle OS validation
+            if [ -f "$PKG_DIR/dep/uname" ] ; then
+              printf "INFO: validating OS requirements... "
+              grep `uname` < "$PKG_DIR/dep/uname" > /dev/null
+              if [ $? -eq 0 ] ; then
+                echo "OK"
+              else
+                echo "ERROR: OS `uname` is not supported by this package!"
+                exit 1
+              fi
+            fi  # if [ -f "$PKG_DIR/dep/uname" ] ; then
+  
+            # attempt to download any artifacts required
+            if [ -f "$PKG_DIR/dep/remote" ] ; then
+              mkdir "$PKG_DIR/remote"
+              DOWNLOAD_CMD="$NET_CDANIELS_TOOLCHEST_DIR/bin/download"
+              if [ ! -f "$DOWNLOAD_CMD" ] ; then
+                echo "ERROR T789: unable to locate download command"
+              else
+                while read -r line ; do
+                  ARTIFACT_NAME=`echo $line | cut -d\  -f 1`
+                  ARTIFACT_URL=`echo $line | cut -d\  -f 2`
+                  echo "INFO: preparing to download dependancy: $ARTIFACT_NAME"
+                  "$DOWNLOAD_CMD" "$ARTIFACT_URL" "$PKG_DIR/remote/$ARTIFACT_NAME"
+                  if [ $? -eq 0 ] ; then
+                    echo "INFO: successfully downloaded dependancy $ARTIFACT_NAME."
+                  else
+                    echo "ERROR: FAILED to download dependancy $ARTIFACT_NAME"
+                  fi
+                done < "$PKG_DIR/dep/remote"
+              fi  # if [ ! -f "$DOWNLOAD_CMD" ] ; then
+            fi  # if [ -f "$PKG_DIR/dep/remote" ] ; then
+  
+            # perl modules
+            if [ -f "$PKG_DIR/dep/perl" ] ; then
+              while read -r line ; do
+                  printf "INFO: validating perl module \"$line\"... "
+                  perldoc -l "$line" > /dev/null 2>&1
+                  if [ $? -ne 0 ] ; then 
+                      echo "FAIL"
+                      echo "ERROR: perl module \"$line\" is not present!"
+                      exit 1
+                  else
+                      echo "DONE"
+                  fi
+              done < "$PKG_DIR/dep/perl"
+            fi  # if [ -f "$PKG_DIR/dep/perl" ] ; then
 
         fi  # if [ -e "$PKG_DIR/dep" ] ; then
 
