converted tabs to spaces in bin/toolchest

diff --git a/bin/toolchest b/bin/toolchest
--- a/bin/toolchest
+++ b/bin/toolchest
@@ -853,14 +853,14 @@ case "$DIRECTIVE" in
         fi
       fi
     done
-	printf "INFO: validating realpath in PATH... "
-	command -v realpath > /dev/null
-	if [ $? -ne 0 ] ; then
-	  echo "FAIL"
-	  printf "INFO: symlinking normalize-path to realpath..."
-	  ln -s $NET_CDANIELS_TOOLCHEST_DIR/bin/normalize-path $NET_CDANIELS_TOOLCHEST_DIR/bin/realpath
-	fi
-	echo "DONE"
+  printf "INFO: validating realpath in PATH... "
+  command -v realpath > /dev/null
+  if [ $? -ne 0 ] ; then
+    echo "FAIL"
+    printf "INFO: symlinking normalize-path to realpath..."
+    ln -s $NET_CDANIELS_TOOLCHEST_DIR/bin/normalize-path $NET_CDANIELS_TOOLCHEST_DIR/bin/realpath
+  fi
+  echo "DONE"
     touch "$NET_CDANIELS_TOOLCHEST_DIR/local/config/setup-done"
     echo "INFO: setup finished successfully"
   ;;
