moved the repoman tool into its own package while it is being developed

diff --git a/packages/net.cdaniels.toolchest.indev/repoman/bin/repoman b/packages/net.cdaniels.toolchest.indev/repoman/bin/repoman
--- a/packages/net.cdaniels.toolchest.indev/repoman/bin/repoman
+++ b/packages/net.cdaniels.toolchest.indev/repoman/bin/repoman
@@ -15,9 +15,9 @@
 # 
 # Directives: 
 # 
-# list-active . . . . . list currently active repositories
+# list-active . . . . . List currently active repositories.
 # 
-# list-installed  . . . list all installed repositories 
+# list-installed  . . . List all installed repositories.
 # 
 # install [url] . . . . If the URL is a git repository, it will be cloned into 
 #                       the repo storage directory. 
@@ -27,9 +27,15 @@
 # 
 # deactivate [repo] . . Deactivate a repository (removes symlink only, does
 #                       not delete). The toolchest will uninstall any packages
-#                       present in the repo
+#                       present in the repo.
 # 
-# uninstall [repo]  . . delete a repo from disk (use care, no prompt is given)
+# uninstall [repo]  . . Delete a repo from disk (use care, no prompt is given).
+# 
+# update  . . . . . . . For each installed repo, run `repoman update $repo`.
+# 
+# update [repo] . . . . cd into the repo and run `git pull`. If .repoman.cfg
+#                       defines REPOMAN_UPDATE_COMMAND, that will be executed
+#                       instead.
 # 
 # help  . . . . . . . . display this message
 # 
@@ -53,7 +59,11 @@
 #   REPOMAN_REPO_NAME  . . . Explicit name for the repository. Default value
 #                            is the directory name of the top level directory
 #                            of the project.
-# 
+#                            
+#   REPOMAN_UPDATE_COMMAND . Override the command used to update this repo,
+#                            useful if you need to `git pull` from a specific
+#                            branch.
+#   
 # NOTES
 # =====
 # 
@@ -114,19 +124,9 @@ fi
 
 $(acquire-toolchest-dirs)
 
-VAR_DIR="$NET_CDANIELS_TOOLCHEST_LOCAL/var"
-REPOMAN_DIR="$VAR_DIR/repoman"
+REPOMAN_DIR="$NET_CDANIELS_TOOLCHEST_LOCAL/repoman"
 
 # validate the repo storage directory exists
-if [ ! -d "$VAR_DIR" ] ; then
-  echo "INFO: var directory ($VAR_DIR) does not exist, it will be created."
-  mkdir "$VAR_DIR"
-  if [ $? -ne 0 ] ; then
-    echo "ERROR 118: failed to create directory '$VAR_DIR'"
-    exit 1
-  fi
-fi
-
 if [ ! -d "$REPOMAN_DIR" ] ; then
   echo "INFO: repoman directory ($REPOMAN_DIR) does not exist, it will be created."
   mkdir "$REPOMAN_DIR"
@@ -146,9 +146,38 @@ case "$DIRECTIVE" in
   ;;
 
   activate)
-    # case where the target is a tarball
-    if [ -f "$target" ] ; then
-      START=`pwd`
+    for repo in "$REPOMAN_DIR" ; do
+      REPOMAN_REPO_NAME="`basename $repo`"
+      REPOMAN_REPO_DIR="$repo"
+      if [ -e "$repo/.repoman.cfg" ] ; then
+        . "$repo/.repoman.cfg"
+      if [ "$TARGET" = "$REPOMAN_REPO_NAME" ] ; then
+        ln -s "$repo/$REPOMAN_REPO_DIR" \
+              "$NET_CDANIELS_TOOLCHEST_PACKAGES/$REPOMAN_REPO_NAME"
+        exit
+      fi
+    done
+
+    echo "ERROR 161: failure to activate repository '$TARGET' (did you remember to install it first?)"
+    exit 1
 
   ;;
+
+  install)
+    cd "$REPOMAN_DIR"
+    check-command-exists git
+    if [ $? -ne 0 ] ; then
+      echo "ERROR 170: git is not present on this system, repoman install has been disabled"
+      exit 1
+    fi
+
+    # git clone the repo
+    echo "INFO: retrieving repository... "
+    git clone "$TARGET"
+    if [ $? -ne 0 ] ; then
+      echo "ERROR 176: failue to retrieve repository '$TARGET'"
+      exit 1
+    fi
+    echo "INFO: finished retrieving repository."
+
 esac
